
#### `docker-compose.yml`
```yaml
version: '3'
services:
  backend:
    build: ./backend
    container_name: flask_backend
    command: python app.py
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
